### ISSUE TITLE
Support ESLint 9.0.0

### ISSUE THREAD

**Issue by ghost** [Rantanen/eslint-plugin-xss#15]
This plugin doesn't work with ESLint 9.0.0.

@Rantanen 

Migration guide:
https://eslint.org/blog/2023/11/whats-coming-in-eslint-9.0.0/

**Comment by freaktechnik** [comment]
Sadly even with @eslint/compat this doesn't work yet, and throws the error `context.getSourceCode(...).getComments is not a function` in `xss/no-mixed-html`'s `nodeHasSafeComment`.

**Comment by if1t** [comment]
ESLint: 9.24.0
TypeError: Error while loading rule 'xss/no-mixed-html': Rule must be an object with a `create` method

**Comment by KrzysztofZawisla** [comment]
Bump
